package com.qa.application.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

import java.util.HashSet;
import java.util.Set;

/* E.Records will have autogenerated id, firstname, lastname, occupation, address, mobile number
* E.Records will have bidirectional @OneToOne relationship with User
* E.Records will have bidirectional @ManyToMany relationship with Inspections so both sides will be able to get a list of each other
*
* */
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@Table(name = "employee_records")
public class EmployeeRecords {

    @Id
    @GeneratedValue
    private Integer id;
    @NotBlank()
    private String firstname;
    @NotBlank
    private String lastname;
    @NotBlank
    private String occupation;
    @NotBlank
    private String address;
    @NotBlank
    private String mobileNumber;

    @JsonIgnore
    @OneToOne
    @JoinColumn(name = "user_id")
    private User user;

    @JsonIgnore
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "employee_inspection",
            joinColumns = {@JoinColumn(name = "employee_records_id")},
            inverseJoinColumns = {@JoinColumn(name = "inspection_id")})
    private Set<Inspection> inspections = new HashSet<>();





}
